// The owner-created portrait uses Evandra EE's existing resource name, so
// epilogues and saved actors with that name also resolve the selected artwork.
// No original Evandra artwork is redistributed.
ACTION_FOR_EACH cbmep_cre IN ~RH#EVA~ ~RH#EV25~ ~RH#EVAMP~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%cbmep_cre%.CRE~ BEGIN
    COPY_EXISTING ~%cbmep_cre%.CRE~ ~override~
      PATCH_IF SOURCE_SIZE < 0x2d4 BEGIN
        PATCH_FAIL ~cbm_evandra_portrait: %cbmep_cre%.CRE has a truncated header~
      END
      READ_ASCII 0 cbmep_signature (8)
      PATCH_IF NOT (~%cbmep_signature%~ STRING_EQUAL ~CRE V1.0~) BEGIN
        PATCH_FAIL ~cbm_evandra_portrait: %cbmep_cre%.CRE is not CRE V1.0~
      END
      WRITE_ASCII 0x34 ~rh#evaL~ #8
      WRITE_ASCII 0x3c ~rh#evaL~ #8
    BUT_ONLY
  END
END
COPY ~chriz-bg-modpack/portraits/evandra/rh#eval.bmp~ ~override/rh#eval.bmp~
